# routes.yaml

file_import:
  path: /
  controller: App\Controller\FileImportController::import

files:
  path: /files
  controller : App\Controller\FileImportController::files
  methods: [GET]

files_infos:
  path: /files-infos.json
  controller : App\Controller\FileImportController::filesDataAjax
  methods: [GET]